language: node_js
node_js:
- "10"
dist: trusty
sudo: false

cache:
  directories:
  - node_modules

addons:
  chrome: stable

deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

script:
- npm run lint
- npm run test:headless
- npm run build
- npm run e2e
- npm run build:prod
